//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Levels')
export class LevelsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  levelNumber: number;

  @Column('text', { nullable: true })
  difficulty: string;

  @Column('text', { nullable: true })
  unlockCondition: string;

  @Column('text', { nullable: true })
  powerUps: string;

  @Column('text', { nullable: true })
  upgradeTo: string;
}
