//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Scores')
export class ScoresEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  playerID: number;

  @Column('integer', { nullable: true })
  score: number;

  @Column('integer', { nullable: true })
  level: number;

  @Column('date', { nullable: true })
  dateAchieved: Date;
}
