//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const ScoresTitle = () => {
  const record = useRecordContext();
  return <span>Scores {record ? `"${record.score}"` : ''}</span>;
};

export const ScoresList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="playerID" reference="Players" />
      <NumberField source="score" />
      <ReferenceField source="level" reference="Levels" />
      <DateField source="dateAchieved" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const ScoresEdit = () => (
  <Edit title={<ScoresTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="playerID" reference="Players" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="score" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="level" reference="Levels" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="dateAchieved" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const ScoresCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="playerID" reference="Players" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="score" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="level" reference="Levels" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="dateAchieved" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput
    source="playerID"
    label="playerID"
    reference="Players"
    alwaysOn
  />,
  ,
  <ReferenceInput source="level" label="level" reference="Levels" alwaysOn />,
  ,
];
