//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Players: {
      name: 'Players',
      fields: {
        email: 'Email',
        highScore: 'High Score',
        level: 'Level',
        id: 'id',
      },
    },
    Levels: {
      name: 'Levels',
      fields: {
        levelNumber: 'Level Number',
        difficulty: 'Difficulty',
        unlockCondition: 'Unlock Condition',
        powerUps: 'Power Ups',
        upgradeTo: 'Upgrade To',
        id: 'id',
      },
    },
    Scores: {
      name: 'Scores',
      fields: {
        playerID: 'Player Id',
        score: 'Score',
        level: 'Level',
        dateAchieved: 'Date Achieved',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Players: {
      name: 'Players (fr)',
      fields: {
        email: 'Email (fr)',
        highScore: 'High Score (fr)',
        level: 'Level (fr)',
        id: 'id',
      },
    },
    Levels: {
      name: 'Levels (fr)',
      fields: {
        levelNumber: 'Level Number (fr)',
        difficulty: 'Difficulty (fr)',
        unlockCondition: 'Unlock Condition (fr)',
        powerUps: 'Power Ups (fr)',
        upgradeTo: 'Upgrade To (fr)',
        id: 'id',
      },
    },
    Scores: {
      name: 'Scores (fr)',
      fields: {
        playerID: 'Player Id (fr)',
        score: 'Score (fr)',
        level: 'Level (fr)',
        dateAchieved: 'Date Achieved (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
